### PR TITLE
Description updates

### PR DESCRIPTION
**Pull request by bmcook1**
These changes are based on the description updates/additions discussions the DMP has been discussing.
This also addressed Jaewoo's request for capturing that 'time_occurance' should be required for all OffNominalReport submissions (added description to reflect this requirement, no changes were made to the "required" elements list).
Also, reorganized fet and fet-latency so the primary data models are at the top.

Please review all 3 commits individually.

Thank you,
Brandon

### CODE REVIEW

**Comment by HemilModiARC** [comment]
Good to go.

**Comment by nasajoey** [comment]
@HemilModiARC whatchu doin'?

**Comment by HemilModiARC** [comment]
> @HemilModiARC whatchu doin'?

I was approving edits made by Brandon, it seemed they did not go through, hence try to do that again. Now it seems they all went through twice.

**Comment by bmcook1** [comment]
Are we ok with these changes? Has been almost 3 weeks since this pull request was created. Would like to merge into develop / master soon. Some of these will help clarify questions we have been getting about data models (units, etc.).

**Pull request merged**
